### ISSUE TITLE
Firefox crashes on file upload

### ISSUE THREAD

**Issue by jappe999** [pqina/filepond-plugin-image-preview#9]
I'm running Firefox Developer Edition 64.0b9 and when I upload a file using Filepond, Firefox crashes. See the GIF below. In the GIF you can see the Codepen example that can be found on https://pqina.nl/filepond/#multi-file-code.

![tab-crash](https://user-images.githubusercontent.com/10500389/48629314-90102980-e9b9-11e8-8e2d-8d56b0876691.gif)

**Comment by rikschennink** [comment]
Thanks for reporting, I'm aware of the issue, but, no idea why thus far.

**Comment by rikschennink** [comment]
Just published version `3.1.4` which fixes this issue.

Turns out, Firefox Nightly/Dev crashed when sending an object URL (`URL.createObjectURL(file)`) to a WebWorker and using `fetch(objectUrl).then(res => res.blob())` to turn it back into a `file` again.

I'm not sure why I initially set it up with object URLs as it's also possible to send File objects to WebWorkers.

**Comment by rikschennink** [comment]
Please confirm it's solved

**Comment by jappe999** [comment]
Thank you so much!
